### ISSUE TITLE
Write message selectors

### ISSUE THREAD

**Issue by ryanj** [ryanj/commander-1k#8]
Write functions to select each relevant status messages, before broacasting them on our outbound websocket

**Comment by ryanj** [comment]
Requires #7 - Add a watcher for 'watchPods' or 'events'

**Comment by ryanj** [comment]
Broadcast each of the following status changes:
- [ ] **1. Awaiting:** Call the API to 1000x provision the initial image [doodlepods](https://github.com/ryanj/doodlepod) #14 
- [x] **2. Pending:** We should see a stream of updates to indicate the Pod requests have been queued and are in progress #7 #8 (~1-5mins?)
- [x] **3. Provisioning:** Add a service for each replicated pod, then add a Route
- [x] **4. Routing:** Add a public Route. Wait 5 seconds after completing step one to let things settle a bit. #15 (~1-10 seconds?)
- [x] **5. Live:** We should get a status update when the pod / container has booted #7 #8 ( wait ~1 second for the webserver to load before checking?)
- [ ] **6. Ready:** Verified to respond with HTTP 200 using a `GET` or `HEAD` request #16 ~3req/second ( check again every 1s for 30s.)

**Comment by ryanj** [comment]
dropping 4 (routing) since it's added during app creation, and it doesn't emit a status when completed.

**Comment by ryanj** [comment]
1 (awaiting), will be triggered on create (no API status to parse)
5/6 (Ready), will be verified via GET (no API status to parse)
